# Generated by Django 3.2.5 on 2021-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('massage', models.TextField(verbose_name='پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
        ),
    ]
