# Generated by Django 3.2.5 on 2021-07-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='neme',
            new_name='name',
        ),
    ]
