# Generated by Django 3.2.5 on 2021-07-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0002_rename_neme_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
    ]
