# Generated by Django 3.2.5 on 2021-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0004_contact_select_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Select_Person',
            field=models.IntegerField(default=1, verbose_name='تعداد افراد'),
        ),
    ]
