# Generated by Django 3.2.5 on 2021-07-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0005_alter_contact_select_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Select_Person',
        ),
    ]
