# Generated by Django 3.2.5 on 2021-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0006_remove_contact_select_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Select_Person',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد افراد'),
        ),
    ]
