# Generated by Django 3.2.5 on 2021-12-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0007_contact_select_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Select_Person',
        ),
    ]
