# Generated by Django 3.2.10 on 2021-12-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0008_remove_contact_select_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('phone_number', models.IntegerField(verbose_name='شماره تلفن')),
                ('number_people', models.IntegerField(default=1, verbose_name='تعداداشخاص')),
                ('theme', models.CharField(choices=[('birth', 'birth'), ('busines', 'busines'), ('appointment', 'appointment'), ('party', 'party')], default='appointment', max_length=50, verbose_name='تم')),
                ('massage', models.TextField(verbose_name='پیام')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
