# Generated by Django 3.2.10 on 2021-12-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysit', '0009_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='شماره تلفن'),
        ),
    ]
