# Generated by Django 3.2.5 on 2021-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(max_length=255, verbose_name='عنوان')),
                ('countent', models.TextField(verbose_name='مطالب')),
                ('countent_views', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('published_date', models.DateField(verbose_name='زمان انتشار')),
            ],
        ),
    ]
