# Generated by Django 3.2.5 on 2021-07-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='countent',
            new_name='content',
        ),
    ]
