# Generated by Django 3.2.10 on 2021-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Type_Food',
            field=models.CharField(choices=[('D', 'drinks'), ('L', 'lunch'), ('DI', 'dinner')], default='D', max_length=50, verbose_name='نوع غذا'),
        ),
    ]
